### ISSUE TITLE
Deborah Digges: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by Deborah-Digges** [weecology/retriever#491] opened 2016-05-23 12:43 UTC
Hello. I am a developer interested to contribute to open science. I have experience with Java and databases and would really like to contribute to this project<p><br><blockquote>This issue was created by @Deborah-Digges via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by Deborah-Digges** [comment] 2016-05-23 12:57
I'm also familiar with python. I could help by adding tests to the project, as a start

**Comment by henrykironde** [comment] 2016-05-23 16:11
Hi @Deborah-Digges , we are glad to hear that you're interested in working with us on the [EcoData Retriever](https://github.com/weecology/retriever). Thank you for that PR contribution #492 . I will be looking at it and we can go from there.

**Comment by ethanwhite** [comment] 2016-05-26 13:33
Hi @Deborah-Digges. Welcome. We're super excited that you're interested in helping out! Your background with Python and databases certainly puts you in a great position to contribute to the project.

I'm Ethan White, I'm a faculty member at the University of Florida. My group does research involving work with large ecological and environmental data, and we also work on making this kind of data-intensive research easier for others by building software like the retriever that automates, and facilitates collaboration on, some of the tedius work of data cleaning, restructuring, and storage. You've already met @henrykironde who is a software engineer in my group and the point person on this project.

We have some basic [developer's docs](https://retriever.readthedocs.io/en/latest/developer.html) which would be worth a quick read if you haven't looked at them already. @henrykironde's done a great job making sure we actually have things like auto-built documentation, but we know they aren't perfect yet so definitely let us know if there are confusing things, issues with getting local testing up and running, etc.

More unit tests are certainly always welcome. We're also happy to chat more about other things that might be good issues for starting to dig into the retriever in more detail.

Finally, I'd like to introduce you to @goelakash. He's a Google Summer of Code student working with us this summer so your likely to see him, @henrykironde, and myself all active over the summer.

So, welcome again and thanks so much for volunteering some of your time to help us help scientists spend more time doing science and less time munging data.

**Comment by Deborah-Digges** [comment] 2016-05-28 04:02
Hello @ethanwhite. Thank you for the warm welcome; it's great to meet you.

@henrykironde @goelakash: I look forward to working with you this summer.

I've read through the developer documentation and was able to install and run the retriever locally. However, I'm facing a bit of an issue with running the tests:

1. **Mysql tests fail with this**: 
`Access denied for user 'travis'@'localhost' (using password: NO) when trying to connect.`

 I have granted privileged to this user for the database `testdb`. Am I missing something?

2. **Postgres tests fail with this**: 
`Couldn't create database (dlopen(/Library/Python/2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found). Trying to continue anyway.` 
I have tried to fix this by following a few posts in [this thread](http://stackoverflow.com/questions/16407995/psycopg2-image-not-found), but haven't been able to.

Any help on the above items would be great! If there are existing issues in the Github project that people have previously raised, which I can refer to for these steps, please do point me to them.

Thank you!

**Comment by henrykironde** [comment] 2016-05-28 05:01
If u look at the documents there is a developer section and the server settings are described. Incase u can't make it work I can have a hangout call with you to set them up.

**Comment by Deborah-Digges** [comment] 2016-05-28 06:40
@henrykironde thank you. I was able to get past 1 & 2. All tests are passing, but for 4 of them, which fail because of the md5 not matching. 

For example, in `check_postgres_regression`, the md5 computed by the script is `bd48125164148e46a90a29a50b66b2c1` for the `MoM2003` dataset, but the expected md5 value is `a55c8308722c8e20950e0d1e6d9639e6`. Have you ever come across this ?

**Comment by Deborah-Digges** [comment] 2016-05-28 06:44
This seems to be related to this issue: https://github.com/weecology/retriever/issues/448.

Do I need the postgresql version to be 9.1? If so, can we mention this in the docs.

**Comment by henrykironde** [comment] 2016-05-28 07:31
@Deborah-Digges, postgres fails if you are not using 9.1 or 9.2.  We plan to update the tests on Monday so that we do not have that dependency of the server versions. For now you could try a hacky way to over come the postgres fails.
```
import os
from unittest import TestCase
from hashlib import md5

import nose


# First md5 is for csv, second md5 is for sqlite
known_md5s = {

    'sqlite': {'AvianBodySize': '72256f681cdce96eba32d4ece270bcb2',
               'DelMoral2010': '2f936afb990c8f818223b27e1e8d6212',
               'MoM2003': 'd3bdce86e0fc5888449884dfb0ef4611'},

    'download': {'AvianBodySize': 'dce81ee0f040295cd14c857c18cc3f7e',
                 'DelMoral2010': '2b6e92b014ae73ea1f0195ecfdf6248d',
                 'MoM2003': 'b54b80d0d1959bdea0bb8a59b70fa871'},

    'csv': {'AvianBodySize': 'f42702a53e7d99d16e909676f30e5aa8',
            'DelMoral2010': 'e79d55ac15f1a70a6c7d3ad4e678ec0e',
            'MoM2003': 'ef0a31c132cfe1c6594739c872f70f54'},

    'mysql': {'AvianBodySize': 'f60ac93d9be4671dbef77da9d10676b8',
              'DelMoral2010': 'f241fd296130512d4e1029376b58a4ea',
              'MoM2003': '9728728d72af4c21a2a6e29fec3edb48'},

    # 'postgres': {'AvianBodySize': '60c252af74d914e3c15fa9af43edefca',
    #              'DelMoral2010': '63d91a972b5ca07bf90900a576286a8a',
    #              'MoM2003': 'a55c8308722c8e20950e0d1e6d9639e6'}
}


def setup_module():
    """Update retriever scripts and cd to test directory to find data"""
    os.chdir("./test/")
    os.system("retriever update")


def teardown_module():
    """Cleanup temporary output files after testing and return to root directory"""
    os.system("rm output_*")
    os.system("rm -r raw_data/MoM2003")
    os.chdir("..")


def getmd5(file_path):
    """Get MD5 of a file, files in a directory or for specific files"""
    files = []
    if os.path.isfile(file_path):
        files.append(file_path)
    elif os.path.isdir(file_path):
        for root, directories, filenames in os.walk(file_path):
            for filename in sorted(filenames):
                files.append(os.path.normpath(os.path.join(root, filename)))
    sum = md5()
    for file_path in files:
        lines = open(file_path, 'rU')
        sum = md5()
        for line in lines:
            sum.update(line)
    return sum.hexdigest()


def unixfileformat(inputfile):
    unix_outfilename = 'output_fileunix'
    content = ''
    try:
        with open(inputfile, 'rb') as infile:
            content = infile.read()
        with open(unix_outfilename, 'wb') as output:
            for line in content.splitlines():
                output.write(line + '\n')
        infile.close()
        output.close()
    except IOError as e:
        print "I/O error({0}): {1} ".format(e.errno, e.strerror)
    return unix_outfilename


def _test_factory(test_method, name, *args):
    stub_test = lambda self: getattr(self, test_method)(*args)
    stub_test.func_name = stub_test.__name__ = 'test_%s' % dataset
    return stub_test


class SqliteRegression(TestCase):

    def check_sqlite_regression(self, dataset, known_md5):
        """Check for regression for a particular dataset imported to sqlite"""
        os.system("rm output_database")  # reinstalling changes checksum in sqlite
        os.system("retriever install sqlite %s -f output_database" % dataset)
        os.system("echo .dump | sqlite3 output_database > output_file")
        current_md5 = getmd5(unixfileformat("output_file"))
        assert current_md5 == known_md5


class CSVRegression(TestCase):

    def check_csv_regression(self, dataset, known_md5):
        """Check for regression for a particular dataset imported to csv"""
        os.system("rm output_file*")
        os.system("retriever install csv %s -t output_file_{table}" % dataset)
        os.system("cat output_file_* > output_file")
        current_md5 = getmd5('output_file')
        assert current_md5 == known_md5


class MySQLRegression(TestCase):

    def check_mysql_regression(self, dataset, known_md5):
        """Check for regression for a particular dataset imported to mysql"""
        os.system("rm output_file*")
        os.system('mysql -u travis -Bse "DROP DATABASE IF EXISTS testdb"') # installing over an existing database changes the dump
        os.system("retriever install mysql %s -u travis -d testdb" %dataset)  # user 'travis' for Travis CI
        os.system("mysqldump testdb -u travis --compact --compatible=no_table_options --no-create-db --no-create-info --result-file=output_file")
        current_md5 = getmd5(unixfileformat("output_file"))
        assert current_md5 == known_md5


class PostgreSQLRegression(TestCase):

    def check_postgres_regression(self, dataset, known_md5):
        """Check for regression for a particular dataset imported to postgres"""
        os.system("rm output_file*")
        os.system('psql -U postgres -d testdb -h localhost -c "DROP SCHEMA IF EXISTS testschema CASCADE"')
        os.system("retriever install postgres %s -u postgres -d testdb -a testschema" % dataset)
        os.system("pg_dump -n testschema --data-only -U postgres -h localhost -f output_file testdb")
        current_md5 = getmd5(unixfileformat("output_file"))
        assert current_md5 == known_md5


class DownloadRegression(TestCase):

    def check_download_regression(self, dataset, known_md5):
        """Check for regression for a particular dataset downloaded only"""
        os.system("retriever download {0} -p raw_data/{0}".format(dataset))
        current_md5 = getmd5("raw_data/%s" % (dataset))
        assert current_md5 == known_md5


dbms_test_classes = {'sqlite': SqliteRegression, 'csv': CSVRegression,
                     'mysql': MySQLRegression,
                     # 'postgres': PostgreSQLRegression,
                     'download': DownloadRegression}

for dbms in known_md5s:
    for dataset in known_md5s[dbms]:
        stub_test = _test_factory('check_%s_regression' % dbms, 'test_%s' % dataset,
                                  dataset, known_md5s[dbms][dataset])
        setattr(dbms_test_classes[dbms], stub_test.__name__, stub_test)
        del(stub_test)

if __name__ == '__main__':
    nose.runmodule()

```

**Comment by Deborah-Digges** [comment] 2016-05-28 07:39
Thanks @henrykironde. this works! 
One question: how are these `known md5 values` computed?

**Comment by henrykironde** [comment] 2016-05-28 08:06
basically they are precompute after downloading the files using the retriever. you can actually try using md5sum [filename]

I know sometimes you may get different values based on the operating system that you are using. Different operating systems handle files in different ways. for example the Carriage return. As a result you may end up getting different hashes. To try out a sample using MoM2003   download the file using `retriever download MoM2003 `. Rum Md5sum on the file and see what you are getting.   

We created [getmd5](https://github.com/weecology/retriever/blob/master/test/test_regression_cli.py#L46)  that calculates the hashes

**Comment by henrykironde** [comment] 2016-05-28 08:08
Based on the [mode](https://github.com/weecology/retriever/blob/master/test/test_regression_cli.py#L57) you use to open the file, You are bound to get different hashes

**Comment by goelakash** [comment] 2016-05-28 09:48
@Deborah-Digges Just don't use Windows and you'll be fine wrt the md5 hashes :+1:

**Comment by ethanwhite** [comment] 2016-06-02 16:44
@Deborah-Digges Thanks again for your contributions so far. We really appreciate it.

I've been looking through our issue queue identifying ones that might make good next steps (no rush of course, just trying to surface things that might be both tractable and valuable as you get familiar with the code base). Here's a list with some possibilities:

1. #290 and #291. We currently run into a RAM limit when downloading large datasets because we are reading the entire file in order to clean the line endings. #291 proposes a solution to this and #321 by @jamesaq was intended to solve this problem but was causing some tests to fail and never ended up being finished.
2. #168 SQL INSERT statements use custom quoting rather than parameter binding. Basically just improve how we interact with SQL database management systems from Python.
3. #312 Optimize `add_to_table` by inserting chunks of data instead of one line at a time. This would involve adding some of the logic from https://github.com/weecology/retriever/commit/bc182e42d6e73c1a20a71ce6ad83604c4b463084 to `add_to_table`.
4. #137 Add a Python interface. Currently our main UI is through the command line. It would be nice to have a Python interface as well. We have a model of what that interface looks like in R (see https://github.com/ropensci/ecoretriever), though in this case since Python is the core language we don't want to wrap the CLI, but call the same components internally.

Of course you are free (and encouraged) to help out with anything you'd like. I just know that sometimes it can be helpful to have a list like this when getting started with a new project.

I also wanted to mention that we've recently set up a [Gitter chatroom](https://gitter.im/weecology/retriever). Issues are totally fine as a venue for general discussion, but if you prefer chat for some things that's available as well.

**Comment by Deborah-Digges** [comment] 2016-06-03 14:46
Thanks for this list of things that need help, @ethanwhite. It's definitely useful to have!
I'd really like to start working on Item #1. I'll go through the existing PR and come back with questions, if I have any.

Thank you, again 👍

**Comment by ethanwhite** [comment] 2016-06-25 14:50
@Deborah-Digges I'm going to go ahead and close this issue since we're well introduced now. Thanks again for your contributions so far and we look forward to seeing you around.

**Closed by ethanwhite** 2016-06-25 14:50 UTC
