### ISSUE TITLE
Refactor add to table function in the engine module

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#645] opened 2016-09-12 21:32 UTC
Currently the [engine](https://github.com/weecology/retriever/blob/master/lib/engine.py) module has a function that loops through the lines to be inserted, it cleans them up and makes them ready for insert.

This all happens in the function   `add_to_table()` with over 100 lines of code.
We need to refactor this module as much as we can to make maintaining easy.

**Comment by ethanwhite** [comment] 2017-01-15 03:51
Closing as duplicate of #584.

**Closed by ethanwhite** 2017-01-15 03:51 UTC
