### ISSUE TITLE
problems accessing Portal Mammals dataset as csv

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#327] opened 2015-07-26 18:16 UTC
Just installed Retriever v1.7.0 and tried downloading Portal Mammal dataset as csv files on a Windows 7 machine.

Data in PortalMammals_main.csv gets shifted relative to column headers. Part of this is because the first two field names are 'record_id' and 'recordid', while there is only actually one column with record id's. 

The PortalMammals_species.csv table gets created (as in, the filename appears in Windows Explorer), but it's size is 0 and Retriever never seems to finish with it (can only open it as Read-Only because it says another it is being used by another user).

Downloading this dataset into MS Access worked fine however.

Probably unrelated and a separate issue, but EcoData Retriever only opens on my machine 50% of the time. The other 50%, I get the opening window and it displays the loading of all the dataset scripts but then both windows immediately close.

**Comment by ethanwhite** [comment] 2015-07-27 12:33
Thanks for the report @ahhurlbert.

> Probably unrelated and a separate issue, but EcoData Retriever only opens on my machine 50% of the time. The other 50%, I get the opening window and it displays the loading of all the dataset scripts but then both windows immediately close.

Can you file this as a separate issue since it's definitely a different (and new) problem. Thanks.

**Comment by ethanwhite** [comment] 2015-07-27 12:36
@ahhurlbert - I can replicate the issue with `PortalMammals_main.csv`, but haven't yet been able to reproduce the issue with `PortalMammals_species.csv`. Can you run that one more time just to make sure it's reproducible on your end before I start digging into that one. Thanks.

**Comment by ahhurlbert** [comment] 2015-07-27 12:39
Both files were problematic as described above on two occasions on one machine, and on another occasion using a different machine. (First machine Windows 7 Enterprise, second machine Windows 7).

**Comment by ethanwhite** [comment] 2015-07-27 12:40
OK, thanks!

**Comment by ethanwhite** [comment] 2015-07-27 12:45
@ahhurlbert - can you try installing this from the command line using:

```retriever install csv PortalMammals```

and paste the output here. This command should work in either GitBash or the Windows command prompt for 1.7. Thanks.

**Comment by ahhurlbert** [comment] 2015-07-27 12:48
Last 2 rows of command line output: 

Inserting rows to c:/Users/hurlbert\Desktop\PortalMammals_main.csv: 35549 / 35549
Inserting rows to c:/Users/hurlbert\Desktop\PortalMammals_species.csv: 55 / 55
Done!

**Comment by ethanwhite** [comment] 2015-07-27 13:04
Thanks. Does `PortalMammals_species.csv` have data in it now?

**Comment by ahhurlbert** [comment] 2015-07-27 13:52
Yes!

**Comment by ethanwhite** [comment] 2015-07-27 14:08
OK, I've now run down the issue with no data in the species table. To reproduce:

1. Install a multi-table dataset using the GUI, do not close the GUI.
2. Check the last file in the dataset, it will be empty.

If you close the GUI the file should then have data in it (tested on Windows & and Ubuntu 15.04).

So, the bug has to do with not closing the file connection to the last file in a multi-file dataset when using the GUI.

@ahhurlbert - you should be able to just close the GUI and be all set, but this is definitely something we need to fix. Thanks again for reporting!

**Comment by ethanwhite** [comment] 2015-07-27 15:06
The issues with Portal should be fixed by #329 and #330.

**Comment by ethanwhite** [comment] 2015-07-27 15:18
This is fixed in 990035836ddd5206c62ddd4da1cd6eca1cca018f and e793881d571df544514354e067cf176a0a46cc2d. I've opened #331 to address the potentially more general issues with skipping fields and @ahhurlbert opened #328 to cover the GUI opening issues, so I'm going to go ahead and close this.

**Closed by ethanwhite** 2015-07-27 15:18 UTC
